apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: support-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: support
    spec:
      containers:
      - image: tomisebjanic/rso-support:1.0.4
        name: support
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres:5432/rsousers
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://support:8088
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 60
          periodSeconds: 3
        ports:
        - containerPort: 8088
          name: server
          protocol: TCP
        resources:
          requests:
            cpu: 150m

---

apiVersion: v1
kind: Service
metadata:
  name: support
  labels:
    app: support
spec:
  type: NodePort
  ports:
  - name: server
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: support

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: support
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: support-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50